export const HOME_RECOMMENDATION_REVALIDATE_SECONDS = 12 * 60 * 60;
export const BANGUMI_CALENDAR_FRESH_SECONDS = 6 * 60 * 60;
export const BANGUMI_CALENDAR_MAX_AGE_SECONDS = 24 * 60 * 60;
export const BANGUMI_CALENDAR_STALE_SECONDS =
  BANGUMI_CALENDAR_MAX_AGE_SECONDS - BANGUMI_CALENDAR_FRESH_SECONDS;
